# https://github.com/crate-ci/typos # LSP: https://github.com/tekumara/typos-lsp
# install:  cargo install typos-cli
# run:      typos
[default]
extend-ignore-identifiers-re = [
    # Allow all-caps words that are 2-letters or more and ends with 's'
    "[A-Z]{2,}s",
]
extend-ignore-re = [
    # Ignore CLIENT_ID=<random letters>
    "CLIENT_ID=[A-Za-z0-9_-]+",
    # PowerShell's case-insensitive inequality operator
    '\B-ine\b',
]

[default.extend-identifiers]
PnP = "PnP"
