# Publishes our workspace's crates to crates.io
#
# This is triggered automatically by dist during the publish step
# (this is a custom publish job: https://axodotdev.github.io/cargo-dist/book/ci/customizing.html#custom-jobs)
#
# It is assumed that all crates are versioned and released in lockstep,
# and that the current commit we're working on already has them at the right version
# to publish.
#
# By default this is invoked only for non-prereleases, because we don't
# want to clutter up crates.io with a million prereleases (and cratesio gives less useful
# download stats if you have lots of prereleases).
name: PublishRelease

on:
  workflow_call:
    inputs:
      plan:
        required: true
        type: string

jobs:
  # publish the current repo state to crates.io
  cargo-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - run: cargo publish -p axoproject --token ${CRATES_TOKEN}
        env:
          CRATES_TOKEN: ${{ secrets.CRATES_TOKEN }}
      - run: cargo publish -p cargo-dist-schema --token ${CRATES_TOKEN}
        env:
          CRATES_TOKEN: ${{ secrets.CRATES_TOKEN }}
      - run: cargo publish -p cargo-dist --token ${CRATES_TOKEN}
        env:
          CRATES_TOKEN: ${{ secrets.CRATES_TOKEN }}
